spring.application.name=demo
# ?? Spring Boot ?? Redis ???
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

# ?? Spring Boot ???? AI ??????
langchain4j.open-ai.chat-model.base-url=https://open.bigmodel.cn/api/paas/v4/
# ???????? API Key
langchain4j.open-ai.chat-model.api-key=6e39ae6d74324048ba945916fcd4e2ab.qIXyhns5lSGYJnty
# ??????????glm-4 ???????????
langchain4j.open-ai.chat-model.model-name=glm-4